### ISSUE TITLE
Issue with Widget

### ISSUE THREAD

**Issue by engram-design** [alecritson/Placid#11]
When trying to add a new widget to the Dashboard (there are currently no other widgets), the following error is thrown:

![screen shot 2015-06-12 at 2 12 11 pm](https://cloud.githubusercontent.com/assets/1221575/8123462/27758cd6-110d-11e5-951f-6d7e079da7a8.png)

**Comment by engram-design** [comment]
Okay - so a quick fix for this is to add a `_widgets` folder and a `placid` folder inside that to your site's templates directory.

**Comment by alecritson** [comment]
Ahh thanks for pointing this out, yeah I need to improve the widgets functionality, to allow for better fallback/customisation of where your widget templates are stored.

**Comment by alecritson** [comment]
With update [`1.3.9`](https://github.com/alecritson/Placid/releases/tag/1.3.9) This exception should no longer happen. You can also specify where your request templates live in the plugin settings.

**Comment by engram-design** [comment]
@alecritson Awesome! Love your work :+1:
