### ISSUE TITLE
Recoverable Error

### ISSUE THREAD

**Issue by andrewlphilpott** [alecritson/Placid#13]
Hello,

I'm using Placid 1.4.0 in combination with OAuth 0.9.72. I believe all of my settings are correct for a request that I'm trying to set up, but when I try to make the request in my template, I get the following error: 

Argument 1 passed to Dukt\OAuth\base\Provider::setToken() must be an instance of Craft\Oauth_TokenModel, null given, called in /Users/andrew/Repos/Emerge/craft/plugins/placid/services/Placid_RequestsService.php on line 447 and defined

Is there anything off the bat that I should try to fix this?

Thanks,
Andrew Philpott

**Comment by alecritson** [comment]
Hey @andrewlphilpott 

I've actually just been working on Placid and using the Twitter API. I can't say I have come across this error :confused: 

Which provider are you trying to authenticate to? Could also provide any template code and/or screenshots of the request in the admin area?

**Comment by alecritson** [comment]
Also, if you have access to your database, look in `craft_placid_oauth`, are there any records in there?

**Comment by andrewlphilpott** [comment]
Hmm, I took a look in the `craft_placid_oauth_tokens` table and I thought there were records in there. I could be wrong, though. I actually ended up uninstalling Placid and using Guzzle for the feeds I was trying to set up (Facebook and Vimeo) so I don't have that table anymore.

**Comment by alecritson** [comment]
Oh Okay sure, I just had a go and managed to get things working for myself, so if you decide to go back here are the steps/settings I used:

**Facebook**  

- Create an app in facebook, add using the OAuth plugin and then connected through placid
- Added a request with these attributes:
  - name: Facebook
  - handle: facebook
  - url : `https://graph.facebook.com/v2.4/<pageId>/feed`
  - authentication - Choose facebook from dropdown

Used `{% set api = craft.placid.request('facebook') %}` in templates, got the feed back.

**Vimeo**
- Same as facebook in regards to setting up authentication
- Added request with these attributes:
  - name: Vimeo
  - handle : vimeo
  - url: `https://api.vimeo.com/me`
  - authentication - Choose vimeo from dropdown

Used `{% set api = craft.placid.request('vimeo') %}` in templates, got my vimeo profile back.

Once you have added your providers to the OAuth plugin, you can go to `admin/placid/oauth` and press the `connect to {provider}` buttons. Just make sure your callback url (set on the website you are authenticating to) is exactly the same as your website url.

If you don't get anything back or get errors, you can open up the Craft log and you should see anything wrong thats going on.

I hope that helps.

**Comment by andrewlphilpott** [comment]
Sweet. I'll give this a try tomorrow morning. Thanks!
