### ISSUE TITLE
500 error when accessing request via AJAX

### ISSUE THREAD

**Issue by mcclaskiem** [alecritson/Placid#14]
I am currently trying to access a request in Placid via JS on the front-end.

I structured my AJAX the same as the docs mention:

        $.get('{{ actionUrl('placid/requests/request', { handle : 'githubContributor'}) }}', function(response){
            console.log(response);
        });

In the client console I am getting a 500 Error

On the craft logs I get this error:
`exception 'CException' with message 'Craft\Placid_RequestsService and its behaviors do not have a method or closure named "setOptions".' in .../craft/app/framework/base/CComponent.php:266`

Is this an issue with the request formatting or an issue with the plug-in?

**Comment by alecritson** [comment]
Hey @mcclaskiem 

Looks like you found a bug, thanks for brining this up. Just pushing a fix now :+1:

**Comment by alecritson** [comment]
If you download version [`1.5.2`](https://github.com/alecritson/Placid/releases/tag/1.5.2) and update placid, this should hopefully be resolved.

**Comment by mcclaskiem** [comment]
@alecritson Thanks very much for the quick fix!
