### ISSUE TITLE
Stuck in database upgrade loop after 2.5 upgrade

### ISSUE THREAD

**Issue by divan-moller** [alecritson/Placid#17]
I upgraded to Craft 2.5.2754, ran into an issue that rendered my dashboard unusable, dev mode pointed out that it was caused by Placid.

![image](https://cloud.githubusercontent.com/assets/3006505/11736408/ba9da284-9fd6-11e5-849b-fff33faf2d79.png)

I then upgraded Placid by deleting the plugin files and replacing them with the latest https://github.com/alecritson/Placid/commit/67a2ca68866b552e550e24eefd20b8403d52ff60

I was prompted to upgrade the database, which succeeded. I am then warned that there were some deprecation errors that I should review.

![image](https://cloud.githubusercontent.com/assets/3006505/11736481/9169fb00-9fd7-11e5-9caf-49435730c7b2.png)

Clicking that repeats the database upgrade. If I try and use any feature in my Craft Admin Panel I am returned to the database update page for the Placid upgrade. Completing this upgrade makes no difference. All features keep redirecting here.

![image](https://cloud.githubusercontent.com/assets/3006505/11736439/128cb6ce-9fd7-11e5-9f8a-96119729de6a.png)

**Comment by alecritson** [comment]
Hey @divan-moller 

This is a strange one, I haven't had any issues with Placid and the new Craft yet myself, i'm currently running `1.6.10` and `2.5.2754`.

With the screenshot, was their a message at the top that could have any indication of what was causing the error? It seems to have been cut off slightly.

Have you tried to add any widgets or did you have any Placid widgets before the update?

I just tried to add widgets and do other admin things and didn't get any deprecation errors or dashboard lock outs :/. 

If you look in your database, in the table `craft_plugins` there should be a Placid row, is the version in the database matching the latest version you downloaded?

**Comment by alecritson** [comment]
@divan-moller Are you still having issues?

**Comment by divan-moller** [comment]
Hi Alec, apologies for the silence. I've finally managed to track the problem down. Happy to report it is not a Placid plugin issue. What had happened was two sites were pointing at the database, due to a db config file being overwritten in a test environment. So two Craft sites with different versions of plugins were causing issues with both Craft itself and Placid.
