### ISSUE TITLE
Expired token for Facebook

### ISSUE THREAD

**Issue by vegardsando** [alecritson/Placid#19]
So here I am again with this issue. I noticed that all of a sudden, the facebook posts didn't appear as they used to. And after debugging a bit, I found that the facebook placid object was NULL. So I checked the placid.log and found it got a 400 Bad Request response.

I then copied the URL it tries to collect from and got this response from Facebook Graph:

"Error validating access token: Session has expired on Sunday, 27-Dec-15 02:10:15 PST. The current time is Monday, 04-Jan-16 04:59:02 PST."

How can I make sure it creates a new token? I tried disabling all caching in Craft. And even flushing everything as well. But no dice.

**Comment by alecritson** [comment]
Hey @vegardsando 

I would have thought this would be handled by the OAuth plugin, I will look into it!

**Comment by alecritson** [comment]
Hey @vegardsando 

It looks like the OAuth plugin should be refreshing the access tokens, do you have an `OAuth` log file of any kind? There could be an error in there?

**Comment by alecritson** [comment]
Hey @vegardsando 

I haven't heard anything so I assume this is solved? I'm going to close this but feel free to reopen.
