### ISSUE TITLE
Response object for widgets doesn't contain useful response

### ISSUE THREAD

**Issue by jonathanmelville** [alecritson/Placid#22]
I upgraded to the latest version of Placid and got a template error for a widget I had created with a Placid request.

Widget looks like this (worked prior to update) and pulls jobs from a job site:
```
<table class="data fullwidth">
     <tbody>
         {% for job in response.jobs %}
         <tr>
             <td>
                 <span class="light">Greenhouse Job ID: {{ job.id }}</span><br>
                 {{ job.title }} - <a href="{{ siteUrl }}careers/{{ job.id }}" target="_blank">View Job</a>
             </td>
         </tr>
         {% endfor %}
     </tbody>
 </table>
```

After update I get this error: `Method "jobs" for object "Guzzle\Http\Message\Response" does not exist `. I dumped the `{{ response }}` object and can see it's a Guzzle response object but it doesn't contain any data from my Placid request.

How can I get this working again?

**Comment by alecritson** [comment]
Hey @jonathanmelville 

Thanks for pointing this out, this was an issue with Placid. If you upgrade to the [1.7.114](https://github.com/alecritson/Placid/releases/tag/1.7.114), this should now be addressed. You will just need to alter your code to something like this:

```twig
<table class="data fullwidth">
     <tbody>
         {% for job in response.data.jobs %}
         <tr>
             <td>
                 <span class="light">Greenhouse Job ID: {{ job.id }}</span><br>
                 {{ job.title }} - <a href="{{ siteUrl }}careers/{{ job.id }}" target="_blank">View Job</a>
             </td>
         </tr>
         {% endfor %}
     </tbody>
 </table>
```

Any issues just let me know :+1:

**Comment by jonathanmelville** [comment]
That did it, thanks so much!!
