### ISSUE TITLE
Authorization Token Bug

### ISSUE THREAD

**Issue by siebird** [alecritson/Placid#27]
Thanks for sharing this plugin–it's awesome. I just came across a bug as I was wondering why I kept getting a `401` status code. It seems storing the authorization string in Placid > Basic Auth > Access tokens  and linking that token to a request does not work.

So I had to move the authorization header to the Placid request headers table to get it to work. Is this not a bug and I am totally missing the intended user for basic auth tokens?

**Comment by alecritson** [comment]
Hey @siebird 

When you create a `Basic Auth` token and attach it to a request, by default Placid [will use the request headers](https://github.com/momentumhq/Placid/blob/master/placid/services/Placid_RequestsService.php#L407), unless you tell specify to force it to go into the query string. Is this option disabled/unselected in the access token edit page?

Also, does the API you are trying to authenticate to expect the header to look like `Authorization: Bearer <YOUR_TOKEN>` ?

**Comment by siebird** [comment]
Hey @alecritson 

Thanks for the quick response. The token's force query string is disabled in the token settings. Once I attach the token to the request is when I ran into issues. Thus, moving the authorization header to the headers table in the request.

The header format is `Authorization: Basic [...string]`

**Comment by alecritson** [comment]
Ahh I see yeah that would be the issue, since Placid is kinda hard coded to use the **Bearer** authorisation method when adding the token to the request, which is obviously different to what your API is expecting.

Unfortunately the best workaround is what you have set up at the moment, but a level of customisation should definitely be considered for future updates. @momentumhq

**Comment by siebird** [comment]
Ahh I see the issue. Line 414 in `services/Placid_RequestsService.php` has `Bearer` hardcoded in. When I was setting the token, I was using the full string `Basic aBcd...`

One way to solve this would be to let users put in the full string like I was doing and remove `Bearer` from being hard coded.

**Comment by siebird** [comment]
Either way is fine with me. I've been setting up services at the most basic endpoint  and then building off that request in the templates with the options path key:

```
{% set api = client.apis.type('beanstalk').first %}
{% set options = {
    path : 'api/changesets/repository.json',
    method : 'GET',
    query : {
        repository_id : api.repositoryId,
        per_page : 30
    }
} %}
{% set revisions = craft.placid.request('beanstalk', options) %}
```

That way I don't need to create a new requests for different endpoints.
