### ISSUE TITLE
Craft 3 Support

### ISSUE THREAD

**Issue by rachelrine** [alecritson/Placid#31]
Any plans to port this for Craft 3 compatibility?

**Comment by jeffjenk** [comment]
Possible alternative depending on your requirements: https://github.com/Dolphiq/craft3-jsonclient

**Comment by torgeirbeyer** [comment]
Would be great if this got updated with Craft 3 compatibility!

**Comment by olivierbon** [comment]
Hey! I'm restarting development for this so I'll let you guys know :)

**Comment by torgeirbeyer** [comment]
Hi. Did you finish developing this for Craft 3? Cant find anything in the plugin store or anywhere else. Thanks.

**Comment by olivierbon** [comment]
I'm working on it :)
