### ISSUE TITLE
Http cache control and etags

### ISSUE THREAD

**Issue by a-am** [alecritson/Placid#4]
Does Placid make use of an api's http cache control & etag  params returned in the http headers?

**Comment by alecritson** [comment]
This isn't something I've consciously added to Placid, at the moment it just utilises Craft's own caching methods. 

Do you have an example of an endpoint and how you would expect this to work in your templates?

**Comment by a-am** [comment]
From my limited understanding, the server should be sending cache headers. The application then should decipher if the request is cached (CacheControl header & ETag to validate) and call for that cached data.  So the templates should work as they currently do, just outputting data received from whatever api that Placid calls. I was wondering if this was happening in the guts of Placid.

**Comment by alecritson** [comment]
Okay sure, I've just taken a look at the Guzzle docs and Craft's own files and it looks like this is a possibility, i'll mark this as another feature request if thats okay with you and look at seeing what I can do when I get some spare time :)
