### ISSUE TITLE
Placid in plugin

### ISSUE THREAD

**Issue by a-am** [alecritson/Placid#5]
Two questions. How do I check to see if Placid is available/installed?  How do I make a Placid call from a plugin?

**Comment by a-am** [comment]
I figured part of it out. 

`craft()->placid_requests->getOptions($options)->request($handle);`

**Comment by alecritson** [comment]
Okay glad you figured part of it out, to then test if the plugin is installed before you make that call you should be able to do something like:

```
$placid = craft()->plugins->getPlugin('placid');

if($placid)
{
  // Make the request
}
```

After reading the Craft docs, it would seem the proper way to utilise a plugin is through [Hooks](http://buildwithcraft.com/docs/plugins/hooks-and-events) for example:

`craft()->plugins->call('request', $options)`

But I think you would run in to problems doing this with Placid as I haven't catered for other plugins to use it's internal workings. I will mark this as a feature request though and definitely consider adding this kind of usage :)
