### ISSUE TITLE
Other OAuth Providers

### ISSUE THREAD

**Issue by engram-design** [alecritson/Placid#6]
Just trying to use Placid to utalize the Instagram API, but at this stage, it seems like you can only use Twitter as a provider under the OAuth tab. There doesn't seem to be a way to add more, or am I missing something?
![screen shot 2015-02-23 at 10 58 04 am](https://cloud.githubusercontent.com/assets/1221575/6321263/df767728-bb4a-11e4-9a6e-9ee0a91f8295.png)

**Comment by alecritson** [comment]
Yes, you're right there isn't a way to add more yet.

You can get Instagram to work but you will need to get an access token an add it through `Basic Auth`, then attach it to a request.

Placid is going through a major overhaul at the moment and high on the list is to provide support for most, if not all, providers that the OAuth plugin offers.

I hope that helps!

**Comment by engram-design** [comment]
No worries, thanks for the reply! I ended up adding it myself, so that's all fine :)

Must say that the plugin is amazing - you've done a great job so far, and look forward to whats next!

**Comment by alecritson** [comment]
Good, glad your sorted out!

Thanks a lot for the feedback! it's good to know that people are finding it useful :)

**Comment by alecritson** [comment]
Just to let anyone know if they see this, the latest release of Placid 1.3.0 does have support for more oauth providers

**Comment by engram-design** [comment]
@alecritson awesome, thanks!
